### ISSUE TITLE
--img Unrecognized arguments

### ISSUE THREAD

**Issue by Max-ChenFei** [Ugness/PiCANet-Implementation#11]
In Execution Example session, It is 

> python Image_test.py --model_dir models/state_dict/07261950/10epo_1000000step.ckpt --img test --cuda cpu
Acutally, I see 

>  parser.add_argument('-img', '--image_dir', help='Directory of your test_image ""folder""', default='../test') in image_test.py

--img is unrecognized arguments. Maybe you should correct the command in execution example.

**Comment by Ugness** [comment]
Oh, I see. I'll correct it.
