### ISSUE TITLE
Error running the code.

### ISSUE THREAD

**Issue by usalexsantos** [Ugness/PiCANet-Implementation#13]
When running the training code I'm getting this error message:

D:\PiCANet_Implementation>python train.py --load /models/state_dict/ --dataset /data/ --cuda cuda --batch_size 1 --epoch 20 -lr 0.001 --lr_decay 0.1 --decay_step 7000 --display_freq 1000
Default path : D:\PiCANet_Implementation
Traceback (most recent call last):
  File "train.py", line 49, in <module>
    duts_dataset = PairDataset(args.dataset)
  File "D:\PiCANet_Implementation\dataset.py", line 121, in __init__
    self.image_list = sorted(os.listdir(os.path.join(root_dir, 'images')))
FileNotFoundError: [WinError 3] The system cannot find the path specified: '/data/images'

Anything I'm doing wrong?

**Comment by Ugness** [comment]
Your directory should be like
data/images/NAME.jpg
data/masks/NAME.jpg.
The error saids you do not have images folder under /data. Please check it again thanks.
