### ISSUE TITLE
How to understand the reshape operator?

### ISSUE THREAD

**Issue by lpengc** [Ugness/PiCANet-Implementation#18]
@Ugness Thanks for your work, I have some question about the Figure 2 (b) and formula 2 of the original paper, could you tell me how do you understand and implement the reshape operation in figure 2 (b)?In my understanding, according to formula (2), if the sum of attention weight after softmax is calculated, wouldn't the attention weight of each position become 1?

**Comment by Ugness** [comment]
![image](https://user-images.githubusercontent.com/33034982/57287482-95da0280-70f2-11e9-933c-c83c3319d61a.png)
I hope this slide would help your understanding. Sorry for the late comment.
For the formula (2), the softmax is calculated in the actual channel C wise, but the sum of attention weight is applied in D (H x W) wise. So it does not become 1.

**Comment by lpengc** [comment]
So the fi in formula 2 can be understood as F, right?

**Comment by lpengc** [comment]
> ![image](https://user-images.githubusercontent.com/33034982/57287482-95da0280-70f2-11e9-933c-c83c3319d61a.png)
> I hope this slide would help your understanding. Sorry for the late comment.
> For the formula (2), since we made a summation of alpha x _f_, not the alpha only, the F_att does not become 1.

So the fi in formula 2 can be understood as F, right?

**Comment by Ugness** [comment]
Yes, you are right.
