### ISSUE TITLE
infer pics with different size

### ISSUE THREAD

**Issue by XChuanLee** [Ugness/PiCANet-Implementation#19]
truely thank you for this implement ^=^ , but it confused me when i want to infer pics with different size.
I run this commend:
'python image_test.py --model_dir=./model/36epo_383000step.ckpt --dataset=./../test/raw_image/ --save_dir=./../test/result_PiCA --batch_size=1'
and I delete 'transforms.Resize((224, 224))' in CustomDataset
but there is always an error.
how can i infer pics with their original size?

**Comment by Ugness** [comment]
I suggest you to inference with size 224 x 224 and resize the output (saliency map) to fit with the original size of the input image.

**Comment by zzzzhe** [comment]
@Ugness I want a solution that outputs the original hd image. Any Suggestions?
