### ISSUE TITLE
Why the output image size is not the same as the input image size

### ISSUE THREAD

**Issue by tuqiangwang** [Ugness/PiCANet-Implementation#23]
Regardless of the input image size, the output image size is always 224x224.
Is this your problem?
OR maybe the method of this paper is inappropriate？

**Comment by mefahimrahman** [comment]
I was going to ask the same problem. I've seen [U-net](https://en.wikipedia.org/wiki/U-Net) architecture. But here I've not found any function which converts the input image size into 224x224. @Ugness can you please explain this?

**Comment by Ugness** [comment]
https://github.com/Ugness/PiCANet-Implementation/blob/master/dataset.py#L117
You can see the input image is cropped to 224x224.

**Comment by Ugness** [comment]
Although U-net like structure is fully Convolutional, 
https://github.com/Ugness/PiCANet-Implementation/blob/master/network.py#L163 needs fixed-size input.

**Comment by mefahimrahman** [comment]
@Ugness I want to change the input and output size then I got "memory error". I changed  
https://github.com/Ugness/PiCANet-Implementation/blob/master/dataset.py#L151 and  
https://github.com/Ugness/PiCANet-Implementation/blob/master/dataset.py#L25 to 640x520. Is there more I've to change to get rid of Memory error?

**Comment by tuqiangwang** [comment]
You may not be able to complete the end-to-end implementation. My suggestion is to implement upsampling interpolation by using tools such as matlab in the later stage.
