### ISSUE TITLE
Testing problems

### ISSUE THREAD

**Issue by githubBingoChen** [Ugness/PiCANet-Implementation#4]
When I use the testing code, I found that you resize the input image and gt in your class DUTS_dataset in Dataset.py as following
**self.transform = transforms.Compose(
            [RandomFlip(0.5),
             RandomCrop(224),
             ToTensor()])**
Could you check whether this is an error  in your testing code?

**Comment by Ugness** [comment]
I thought that same condition on test and training set is fair, but I think that could be an error if you think that resizing is correct for testing. I'll add an testing transform option. Thanks.
