### ISSUE TITLE
 I've met this error at cpu mode

### ISSUE THREAD

**Issue by bemoregt** [Ugness/PiCANet-Implementation#5]
Hi, @pass1825 @Ugness 

I've met this error at cpu mode:

RuntimeError: cannot initialize CUDA without ATen_cuda library

What's wrong with me?

from @bemoregt

**Comment by bemoregt** [comment]
Hi, @pass1825 @Ugness

My Command:

$ python3 image_test.py --cuda 'cpu'

and input image path  is changed with ny image path.

What's wrong with me?

**Comment by Ugness** [comment]
I think your command should be
$ python3 image_test.py --cuda cpu

without quotes. Sorry for making confusion.

**Comment by bemoregt** [comment]
Same error occured.

RuntimeError: cannot initialize CUDA without ATen_cuda library

and

map_location='cpu'

from @bemoregt.

**Comment by Ugness** [comment]
Can you modify the code line 26 
device = torch.device(args.cuda)
to 
device = torch.device('cpu')
?
On my environment, there are no problem. If you show me the code line that error occur, I would help you more.
or please show me the Namespace printout.
In my case,
Namespace(batch_size=4, cuda='cpu', image_dir='../test', logdir='log/Image_test', model_dir='models/state_dict/07121619/0epo_1000step.ckpt')

**Comment by bemoregt** [comment]
JI, @Ugness @pass1825 

OK, Thanks.

I'll try that one.

MacOS X High Sierra, CPU Only, Python 3.6, Pytorch 0.4

from @bemoregt.

**Comment by Ugness** [comment]
In the Namespace, you can see your argument for cuda is 'cuda'.
Namespace(batch_size=4, cuda='cuda', 
Can you run the code with --cuda cpu?
That dashes are double dash(--).
Sorry for asking you to run again. Since my env already have GPU and CUDA, it is hard for me to find error.

**Comment by bemoregt** [comment]
Oh, sheet.
I missed, Sorry.

It works, Thank you.

from @bemoregt.

**Comment by bemoregt** [comment]
HI, @Ugness @pass1825 

At this time, tensorboard not works ..

kerb:Pytorch mun$ tensorboard --logdir=./log/Image_test
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 7, in <module>
    from tensorboard.main import run_main
  File "/usr/local/lib/python3.6/site-packages/tensorboard/main.py", line 28, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/usr/local/lib/python3.6/site-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.6/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python3.6/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.6/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 41, in <module>
    options=None, file=DESCRIPTOR),
TypeError: __init__() got an unexpected keyword argument 'file'
kerb:Pytorch mun$ 

What's wrong with me?

from @bemoregt

**Comment by Ugness** [comment]
ah Sorry. I changed the default log directory to Pytorch/log/Image_test. 
Please check with tensorboard --logdir=./Pytorch/log/Image_test
I'll change the default dir.

**Comment by bemoregt** [comment]
@Ugness @pass1825 님, 안녕하세요?

현재 Pytorch 경로에서 명령어를 날리고 있으므로 
텐서보드 로그경로는 --logdir=./log/Image_test 가 맞을거 같습니다.

경로 문제가 아닌거 같습니다.
아니면, 오히려 Pytorch/ 경로에서 명령어를 날리면 안되는 걸수도 있겠군요.

혹시 PiCANet-Implementation/ 경로에서 텐서보드 명령을 날려야 되는게 아닌지요?

@bemoregt 로부터.

**Comment by Ugness** [comment]
Thanks for asking with Korean.
If you prefer to use Korean, please realize it to me.

I think I do not exactly understand the problem. 
If the directory is wrong, there will be no error message and just blank page.

I think there is no problem with using tensorboard at PiCANet-Implementation/ or not. 
If you have same error, I recommend you to use abstract directory.
ex: D:/Ugness/Python/PiCANet-Implementation/Pytorch/log/Image_test

or please check your tensorboard version.
or try this
`pip install onnx`

**Comment by Ugness** [comment]
Or I'll make the program to make image file output. Not to use tensorboard.
I will add it as soon as possible.

**Comment by bemoregt** [comment]
Great!

ASAP, Please~

**Comment by Ugness** [comment]
I uploaded the file output program as image_test_file_output.py. Please check this. Hope to success~

**Comment by bemoregt** [comment]
Great~!

나의 iPhone에서 보냄

2018. 9. 3. 오후 9:50, Yoo Jaehoon <notifications@github.com> 작성:

**Comment by bemoregt** [comment]
kerb:PiCANet-Implementation mun$ python3 image_test_file_output.py 
Default path : /Users/mun/PICA2/PiCANet-Implementation
Namespace(batch_size=4, cuda='cpu', image_dir='test', logdir='pytorch/images/Image_test', model_dir=None)
/Users/mun/PICA2/PiCANet-Implementation
Traceback (most recent call last):
  File "image_test_file_output.py", line 34, in <module>
    model.load_state_dict(state_dict)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 698, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Unet:
	Missing key(s) in state_dict: "decoder.0.bn_en.num_batches_tracked", "decoder.0.bn_feature.num_batches_tracked", "decoder.1.bn_en.num_batches_tracked", "decoder.1.bn_feature.num_batches_tracked", "decoder.2.bn_en.num_batches_tracked", "decoder.2.bn_feature.num_batches_tracked", "decoder.3.bn_en.num_batches_tracked", "decoder.3.bn_feature.num_batches_tracked", "decoder.4.bn_en.num_batches_tracked", "decoder.4.bn_feature.num_batches_tracked", "decoder.5.bn_en.num_batches_tracked". 
kerb:PiCANet-Implementation mun$ ****

**Comment by Ugness** [comment]
Maybe the error occur because the uploaded model is too old. (before the state_dict commit)
Please try with 14epo_123000step.ckpt. or other 2018.09.01 uploaded models.
If you want some specific step model, please let me know. I'll upload it.

**Comment by Ugness** [comment]
Did the code work well for other models?
And can you explain the map_location='cpu' was necessary for cpu mode? If it is, I'll fix my code.

**Comment by bemoregt** [comment]
Not, Yet ..

Just a wait ~

Thanks.

**Comment by bemoregt** [comment]
It's same.

I used 14epo_123000step.ckpt model at this time.

kerb:PiCANet-Implementation mun$ python3 image_test_file_output.py 
Default path : /Users/mun/PICA2/PiCANet-Implementation
Namespace(batch_size=4, cuda='cpu', image_dir='test', logdir='pytorch/images/Image_test', model_dir=None)
/Users/mun/PICA2/PiCANet-Implementation
Traceback (most recent call last):
  File "image_test_file_output.py", line 34, in <module>
    model.load_state_dict(state_dict)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 698, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Unet:
	Missing key(s) in state_dict: "decoder.0.bn_en.num_batches_tracked", "decoder.0.bn_feature.num_batches_tracked", "decoder.1.bn_en.num_batches_tracked", "decoder.1.bn_feature.num_batches_tracked", "decoder.2.bn_en.num_batches_tracked", "decoder.2.bn_feature.num_batches_tracked", "decoder.3.bn_en.num_batches_tracked", "decoder.3.bn_feature.num_batches_tracked", "decoder.4.bn_en.num_batches_tracked", "decoder.4.bn_feature.num_batches_tracked", "decoder.5.bn_en.num_batches_tracked". 
kerb:PiCANet-Implementation mun$ 

May be Pytorch in Windows10 and MacOSX are so different. --; 

from @bemoregt.

**Comment by Ugness** [comment]
I'll test my code again with drive files soon.
I remember that those kind of errors with state_dict comes from layer name mismatch.
And that error is also case of them.
I'll test my code after 8pm (because I have a schedule), but if you want to debug faster,
please check the weight names with print(model.state_dict().keys()) and print(loaded_state_dict.keys())

**Comment by Ugness** [comment]
It works on my environment. It would be OS problem or CUDA problem. Maybe somewhere still need CUDA in my code.

**Comment by Ugness** [comment]
Please check this issue. It looks similar. [https://github.com/pytorch/ELF/issues/15](https://github.com/pytorch/ELF/issues/15)

**Comment by bemoregt** [comment]
I'm also 0.4.1 upgrded.

Is it a OS Problem ?

--;

**Comment by bemoregt** [comment]
Other Pytorch sources working well in MacOSX.

Windows10 's Pytorch is specific? May be...

**Comment by Ugness** [comment]
Dose the loading error occur in other codes? like train.py or image_test_tensorboard.py

**Comment by Ugness** [comment]
I am going to simulate your environment

> (MacOS X High Sierra, CPU Only, Python 3.6, Pytorch 0.4.1)

 in docker. If I solve the problem, I'll send a mail to you. Thanks.

**Comment by bemoregt** [comment]
Thanks a lot.

2018-09-06 21:38 GMT+09:00, Yoo Jaehoon <notifications@github.com>:

**Comment by Ugness** [comment]
I could not find OSX docker image. But when I test the code in Linux env(https://hub.docker.com/r/pytorch/pytorch), code works. I'll try to upload my own docker image ASAP.
If you want, you can run the code on pytorch/pytorch:latest docker image.

**Comment by Ugness** [comment]
Updated. Check readme.md. But, it's my first time to make docker image, the image is very unstable.
You can just directly run docker with 
```
docker run --name=torch -it -rm pytorch/pytorch
pip install tensorboardX
pip install datetime
git clone https://github.com/Ugness/PiCANet-Implementation
```
