### ISSUE TITLE
How to check the dataset's Image and GT are matched or not. (ex. # of images, name, ...)

### ISSUE THREAD

**Issue by Sucran** [Ugness/PiCANet-Implementation#6]
should I just check the name of image and GT are matched or not ?

**Comment by Ugness** [comment]
Yes. You can easily(?) compare the names by print(os.listdir()). File format(jpg, png) does not matter, but number of datas and name of datas should be matched.

**Comment by Ugness** [comment]
If you think it is hard to match files, I'll make utils/match_data.py for correct DUTS Dataset. as soon as possible.

**Comment by Sucran** [comment]
I think this part need take some time. May be you should make utils/match_data.py for convenience.
The DUT-TR-Image has 10553 jpg images, but DUT-TR-Mask has 10553 png images and 3 jpg images. This 3 jpg have same name with 3 png images in 10553 png images. So, I just delete these 3 jpg images in DUT-TR-Mask.
The DUT-TE-Image has 5019 jpg images, but DUT-TE-Mask has 5021 png images, which has 3 png mask image do not have the matched jpg images in DUT-TE-Image. So, I also delete these 3 png images in DUT-TE-Mask.
So DUT-TR  has 10553 image and matched mask, DUT-TE has 5019 images and matched mask, right?
(all the image name without suffix seems matched, right?)

**Comment by Ugness** [comment]
Yes you are right. There are some over-datas

**Comment by Ugness** [comment]
@Sucran I added arrange method to DUTSdataset class.
